# @package embedder
# Embedder: Nvidia Llama Embed Nemotron 8B

name: nvidia/llama-embed-nemotron-8b
model_class: EMBEDDER
model_type: LLAMA
device: cuda
load_in_8bit: false
load_in_4bit: false
torch_dtype: auto
trust_remote_code: true
max_memory: null
