# @package base_llm
# Base LLM: Llama 3.3 70B Instruct

name: meta-llama/Llama-3.3-70B-Instruct
model_class: BASE_LLM
model_type: LLAMA
device: cuda
load_in_8bit: false
load_in_4bit: false
torch_dtype: bfloat16
trust_remote_code: false
max_memory: null
hidden_size: 8192
num_hidden_layers: 80

# Generation parameters
max_new_tokens: 8192
temperature: null
top_p: null
top_k: null
repetition_penalty: null
no_repeat_ngram_size: null
do_sample: null
num_return_sequences: 8
return_hidden_states: true
return_logits: false

# vLLM settings
vllm_tensor_parallel_size: 3
vllm_gpu_memory_utilization: 0.90
